#!/bin/bash
DIR=recovermypartit-`cat recovermypartition.py | grep 'version="'| cut --delimiter='"'  -f 2`
FILE=$DIR.tar.gz
echo "Este script crea el fichero $FILE para ser subido al proyecto"

mkdir $DIR
mkdir $DIR/i18n

cp      Makefile \
        AUTHORS.txt \
        CHANGELOG.txt \
        GPL-3.txt \
        INSTALL.txt \
        RELEASES.txt \
        recovermypartition.py \
        recovermypartition.pro \
        $DIR

cp      i18n/recovermypartition_es.ts \
        $DIR/i18n

tar cvz $DIR -f $FILE
rm -R $DIR
