.TH RECOVERMYPARTITION 1 2018\-01\-24
.SH NAME

.B recovermypartition:
Восстановите нормальные файлы и удалите файлы из раздела.
.SH SYNOPSIS

recovermypartition [\-\-help] [\-\-version] [\-\-nofiles] [ \-\-nodeleted| \-\-partition| \-\-output ]
.SH ОПИСАНИЕ

.PP
Это приложение имеет следующие параметры.
.PP
.RS
.B \-\-nofiles
.RE
.PP
.RS
.RS
Сканирует сеть параметра интерфейса и распечатывает список обнаруженных устройств.
.RE
.RE
.PP
.RS
.RS
Если устройство неизвестно, оно будет показано красным. Устройства в зеленых являются надежными устройствами.
.RE
.RE
.PP
.RS
.B \-\-nodeleted
.RE
.PP
.RS
.RS
Позволяет добавить известное устройство с консоли.
.RE
.RE
.PP
.RS
.B \-\-partition
.RE
.PP
.RS
.RS
Позволяет удалить известное устройство с консоли.
.RE
.RE
.PP
.RS
.B \-\-output
.RE
.PP
.RS
.RS
Показывает все известные устройства в базе данных с консоли.
.RE
.RE
